services:
  mariadb:
    image: mariadb:10.11
    container_name: keycloak-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloakpass
    ports:
      - "3307:3306"   # MariaDB local port
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: mariadb
      KC_DB_URL_HOST: mariadb
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpass
    ports:
      - "8280:8080"   # Expose Keycloak on 8180 to Ã©viter conflit port
    depends_on:
      - mariadb
    restart: always

volumes:
  mariadb_data:
